version: "3.8"

services:
  app:
    image: europe-docker.pkg.dev/innate-shape-326616/app-proposals-repo/app-proposals:v2
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SECRET_JWT_KEY=${SECRET_JWT_KEY}
      - JWT_EXP=${JWT_EXP}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - APP_PORT=${APP_PORT}
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      #    - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
#volumes:
#  db_data: